#define AMMO_USAGE_NONE 0
#define AMMO_USAGE_LIGHT 1
#define AMMO_USAGE_MARKING 2
#define AMMO_USAGE_CONCEALMENT 4
#define AMMO_USAGE_COUNTERMEASURES 8
#define AMMO_USAGE_MINE 16
#define AMMO_USAGE_UNDERWATER 32
#define AMMO_USAGE_INFANTRY 64
#define AMMO_USAGE_VEHICLES 128
#define AMMO_USAGE_AIRCRAFT 256
#define AMMO_USAGE_ARMORED_VEHICLES 512

#define ATTACHMENTS_POINTER_BASE CLASS(LR_MEQ7_ATTACHMENT) = TRUE; \
CLASS(FL_MEQ7_ATTACHMENT) = TRUE; \
CLASS(MEQ7) = TRUE;

// Special Ammo Types
#define AMMO_TYPE_NORMAL 0
#define AMMO_TYPE_EMP 1
#define AMMO_TYPE_BACTA 2
